- hosts: bigip
  collections:
    - f5networks.f5_bigip
  connection: httpapi

  vars:
    ansible_host: 192.168.86.41
    ansible_user: admin
    ansible_httpapi_password: notarealpassword
    ansible_network_os: f5networks.f5_bigip.bigip
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no

  tasks:
    - name: Install Telemetry
      bigip_lx_package:
        package: f5-telemetry-1.32.0-2.noarch.rpm
        retain_package_file: yes
