- hosts: all
  connection: local
  gather_facts: false

  tasks:
    - name: Check
      uri:
        url: https://192.168.86.41/mgmt/tm/util/bash
        user: admin
        password: notarealpassword
        method: POST
        headers:
          Content-Type: application/json
        body_format: raw  
        body: "{\n\t\"command\": \"run\", \"utilCmdArgs\": \"-c \\\"cd /var/config/rest/downloads/ && curl -sk -LJO https://github.com/F5Networks/f5-telemetry-streaming/releases/download/v1.32.0/f5-telemetry-1.32.0-2.noarch.rpm\\\"\"\n}"
        force_basic_auth: yes
        timeout: 300
        return_content: true
        validate_certs: no
      register: json_response

    - name: printoutput
      debug:
        var: json_response

