- hosts: all
  connection: local
  gather_facts: false

  tasks:
    - name: Check
      uri:
        url: https://192.168.86.41/mgmt/shared/telemetry/declare
        user: admin
        password: notarealpassword
        method: POST
        headers:
          Content-Type: application/json
        body_format: raw  
        body: 
          filename: "{{'splunk.json'}}"
        force_basic_auth: yes
        timeout: 300
        return_content: true
        validate_certs: no
      register: json_response

    - name: printoutput
      debug:
        var: json_response